/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ec.edu.espe.eduplanmaven.view;

/**
 *
 * @author PC
 */
public class PnlGradePlanification extends javax.swing.JPanel {

    private static PnlGradePlanification instance;

    /**
     * Creates new form PnlGradePlanification
     */
    private PnlGradePlanification() {
        initComponents();
    }

    public static PnlGradePlanification getInstance() {
        if (instance == null) {
            instance = new PnlGradePlanification();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbPendingPlans = new javax.swing.JComboBox<>();
        sliderGrade = new javax.swing.JSlider();
        lblGradeValue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPlanDetails = new javax.swing.JTextArea();
        btnGrade = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        progressCompletion = new javax.swing.JProgressBar();
        lblCompletionText = new javax.swing.JLabel();

        cmbPendingPlans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una planificación pendiente" }));

        sliderGrade.setMajorTickSpacing(20);
        sliderGrade.setMaximum(100);
        sliderGrade.setMinimum(1);
        sliderGrade.setMinorTickSpacing(5);
        sliderGrade.setPaintLabels(true);
        sliderGrade.setPaintTicks(true);
        sliderGrade.setValue(80);

        lblGradeValue.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblGradeValue.setForeground(new java.awt.Color(0, 0, 255));
        lblGradeValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGradeValue.setText("80");

        txtPlanDetails.setColumns(20);
        txtPlanDetails.setRows(5);
        txtPlanDetails.setEditable(false);
        txtPlanDetails.setBackground(new java.awt.Color(240, 240, 240));
        txtPlanDetails.setText("Seleccione una planificación para ver los detalles");
        jScrollPane1.setViewportView(txtPlanDetails);

        btnGrade.setBackground(new java.awt.Color(0, 255, 0));
        btnGrade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGrade.setForeground(new java.awt.Color(255, 255, 255));
        btnGrade.setText("Calificar");

        btnCancel.setBackground(new java.awt.Color(255, 0, 0));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancelar");

        progressCompletion.setStringPainted(true);

        lblCompletionText.setText("Progreso de calificaciones del mes:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(progressCompletion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbPendingPlans, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sliderGrade, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGradeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCompletionText)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbPendingPlans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sliderGrade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGradeValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrade)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCompletionText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressCompletion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGrade;
    private javax.swing.JComboBox<String> cmbPendingPlans;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompletionText;
    private javax.swing.JLabel lblGradeValue;
    private javax.swing.JProgressBar progressCompletion;
    private javax.swing.JSlider sliderGrade;
    private javax.swing.JTextArea txtPlanDetails;
    // End of variables declaration//GEN-END:variables

    // Getters for controller access
    public javax.swing.JComboBox<String> getCmbPendingPlans() {
        return cmbPendingPlans;
    }

    public javax.swing.JSlider getSliderGrade() {
        return sliderGrade;
    }

    public javax.swing.JLabel getLblGradeValue() {
        return lblGradeValue;
    }

    public javax.swing.JTextArea getTxtPlanDetails() {
        return txtPlanDetails;
    }

    public javax.swing.JButton getBtnGrade() {
        return btnGrade;
    }

    public javax.swing.JButton getBtnCancel() {
        return btnCancel;
    }

    public javax.swing.JProgressBar getProgressCompletion() {
        return progressCompletion;
    }

    public javax.swing.JLabel getLblCompletionText() {
        return lblCompletionText;
    }
}
