/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to chan        lblMonthlyAverage.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lblMonthlyAverage.setText("Promedio Mensual: --");

        lblPerformanceLevel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPerformanceLevel.setText("Nivel de Desempeño: --");

        lblCompletionStatus.setText("Estado de Completitud: --");

        txtSummary.setColumns(20);
        txtSummary.setRows(5);
        txtSummary.setEditable(false);
        txtSummary.setBackground(new java.awt.Color(240, 240, 240));
        txtSummary.setText("Seleccione un mes y año para generar el reporte");
        jScrollPane2.setViewportView(txtSummary);

        progressBar.setStringPainted(true);
        progressBar.setString("0%");icense
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ec.edu.espe.eduplanmaven.view;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class PnlMonthlyReports extends javax.swing.JPanel {

    private static PnlMonthlyReports instance;

    /**
     * Creates new form PnlMonthlyReports
     */
    private PnlMonthlyReports() {
        initComponents();
        setupTableModel();
    }

    public static PnlMonthlyReports getInstance() {
        if (instance == null) {
            instance = new PnlMonthlyReports();
        }
        return instance;
    }

    private void setupTableModel() {
        String[] columnNames = {"Semana", "ID Planificación", "Nombre", "Calificación", "Estado"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblMonthlyData.setModel(model);
    }

    public DefaultTableModel getTableModel() {
        return (DefaultTableModel) tblMonthlyData.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblSelectPeriod = new javax.swing.JLabel();
        cmbMonth = new javax.swing.JComboBox<>();
        cmbYear = new javax.swing.JComboBox<>();
        btnGenerateReport = new javax.swing.JButton();
        lblTableTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMonthlyData = new javax.swing.JTable();
        lblStatistics = new javax.swing.JLabel();
        lblMonthlyAverage = new javax.swing.JLabel();
        lblPerformanceLevel = new javax.swing.JLabel();
        lblCompletionStatus = new javax.swing.JLabel();
        lblProgressTitle = new javax.swing.JLabel();
        prgMonthlyProgress = new javax.swing.JProgressBar();
        lblSummaryTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSummary = new javax.swing.JTextArea();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Reportes Mensuales de Calificaciones");

        lblSelectPeriod.setText("Seleccionar Período:");

        cmbMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        cmbYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2025", "2026", "2027", "2028" }));

        btnGenerateReport.setText("Generar Reporte");

        lblTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTableTitle.setText("Datos Mensuales");

        tblMonthlyData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Semana", "Planificación", "Calificación", "Estado", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMonthlyData);

        lblStatistics.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatistics.setText("Estadísticas");

        lblMonthlyAverage.setText("Promedio Mensual: --");

        lblPerformanceLevel.setText("Nivel de Rendimiento: --");

        lblCompletionStatus.setText("Estado de Completitud: --");

        lblProgressTitle.setText("Progreso del Mes:");

        prgMonthlyProgress.setStringPainted(true);

        lblSummaryTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSummaryTitle.setText("Resumen Detallado");

        txtSummary.setColumns(20);
        txtSummary.setLineWrap(true);
        txtSummary.setRows(5);
        txtSummary.setText("El resumen detallado del reporte mensual aparecerá aquí...");
        txtSummary.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtSummary);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblSelectPeriod)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGenerateReport))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTableTitle))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatistics)
                            .addComponent(lblMonthlyAverage)
                            .addComponent(lblPerformanceLevel)
                            .addComponent(lblCompletionStatus)
                            .addComponent(prgMonthlyProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProgressTitle)))
                    .addComponent(lblSummaryTitle)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitle)
                .addGap(20, 20, 20)
                .addComponent(lblSelectPeriod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGenerateReport))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTableTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStatistics)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMonthlyAverage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPerformanceLevel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCompletionStatus)
                        .addGap(20, 20, 20)
                        .addComponent(lblProgressTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prgMonthlyProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(lblSummaryTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCompletionStatus;
    private javax.swing.JLabel lblMonthlyAverage;
    private javax.swing.JLabel lblPerformanceLevel;
    private javax.swing.JLabel lblProgressTitle;
    private javax.swing.JLabel lblSelectPeriod;
    private javax.swing.JLabel lblStatistics;
    private javax.swing.JLabel lblSummaryTitle;
    private javax.swing.JLabel lblTableTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JProgressBar prgMonthlyProgress;
    private javax.swing.JTable tblMonthlyData;
    private javax.swing.JTextArea txtSummary;
    // End of variables declaration//GEN-END:variables

    // Getters for controller access
    public javax.swing.JComboBox<String> getCmbYear() {
        return cmbYear;
    }

    public javax.swing.JComboBox<String> getCmbMonth() {
        return cmbMonth;
    }

    public javax.swing.JButton getBtnGenerateReport() {
        return btnGenerateReport;
    }

    public javax.swing.JTable getTblMonthlyData() {
        return tblMonthlyData;
    }

    public javax.swing.JLabel getLblMonthlyAverage() {
        return lblMonthlyAverage;
    }

    public javax.swing.JLabel getLblPerformanceLevel() {
        return lblPerformanceLevel;
    }

    public javax.swing.JLabel getLblCompletionStatus() {
        return lblCompletionStatus;
    }

    public javax.swing.JTextArea getTxtSummary() {
        return txtSummary;
    }

    public javax.swing.JProgressBar getprgMonthlyProgress() {
        return prgMonthlyProgress;
    }
}
